#! /usr/bin/python

# Copyright (c) 2008 Brian Zimmer <bzimmer@ziclix.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import os
import pysmug
import logging
from optparse import OptionParser

fmt = '%(asctime)s|%(name)s|%(levelname)s|%(funcName)s|%(message)s'
logging.basicConfig(format=fmt, level=logging.DEBUG)

logger = logging.getLogger("smugup")

def main(opts, args):
  album = opts.album
  if "_" in album:
    album = album.split("_")[0]
  
  logger.info("using album %s", album)

  m = pysmug.login()
  b = m.batch()
  b.concurrent = 2
  for arg in args:
    logger.info("uploading %s", arg)
    b.images_upload(AlbumID=album, FileName=arg)

  n = len(args)
  for i, (args, result) in enumerate(b()):
    logger.info("uploaded (%d/%d) %s", i, n, result)

if __name__ == '__main__':

  p = OptionParser()
  p.add_option("-a", "--album", dest="album", default=None, action="store", help="the album to store the images")
  opts, args = p.parse_args()

  if not opts.album:
    raise SystemExit()

  main(opts, args)
